### ISSUE TITLE
matpipe benchmark does not work with StratifiedKFold

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/automatminer#191]
bc skf requires y as an arg also

```
Traceback (most recent call last):
  File "/Users/ardunn/alex/lbl/projects/common_env/dev_codes/hmte/projects/003_Air-Sensitivity/src/03_analyze.py", line 31, in <module>
    dfs = pipe.benchmark(df, "air_sensitive", kfold=kf)
  File "/Users/ardunn/alex/lbl/projects/automatminer/automatminer/automatminer/utils/pkg.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ardunn/alex/lbl/projects/automatminer/automatminer/automatminer/pipeline.py", line 231, in benchmark
    for _, test_ix in kfold.split(df):
TypeError: split() missing 1 required positional argument: 'y'
```

**Comment by ardunn** [comment]
fixed (for strict benchmarking) via 20fb5f165ce836ca022788ab9f17165d6c03a6e8
